### ISSUE TITLE
Usage with Next.js and Tamagui

### ISSUE THREAD

**Issue by rdewolff** [acro5piano/react-native-big-calendar#905]
I tried to integrate `react-native-big-calendar` in a repository with Expo and Next.js.

The expo version is working fine, but when rendering the web, I get the following error:
```
yarn web
    at Body (/Users/rdewolff/Projects/meetme/unistack/node_modules/next/dist/server/render.js:666:21)
Warning: ProxyWorm - Check excludeReactNativeWebExports.state: must be set to an object or null
    at ProxyWorm - Check excludeReactNativeWebExports
    at _HourGuideCell (webpack-internal:///../../node_modules/react-native-big-calendar/build/index.js:755:25)
    at div
    at eval (webpack-internal:///../../node_modules/react-native-web/dist/cjs/exports/View/index.js:47:27)
    at div
    at eval (webpack-internal:///../../node_modules/react-native-web/dist/cjs/exports/View/index.js:47:27)
    at div
    at eval (webpack-internal:///../../node_modules/react-native-web/dist/cjs/exports/View/index.js:47:27)
    at div
    at eval (webpack-internal:///../../node_modules/react-native-web/dist/cjs/exports/View/index.js:47:27)
    at eval (webpack-internal:///../../node_modules/react-native-web/dist/cjs/exports/ScrollView/ScrollViewBase.js:60:26)
    at ScrollView (webpack-internal:///../../node_modules/react-native-web/dist/cjs/exports/ScrollView/index.js:36:9)
    at ScrollView
    at _CalendarBody (webpack-internal:///../../node_modules/react-native-big-calendar/build/index.js:817:30)
    at _CalendarContainer (webpack-internal:///../../node_modules/react-native-big-calendar/build/index.js:1378:21)
    at _Calendar (webpack-internal:///../../node_modules/react-native-big-calendar/build/index.js:1534:17)
    at div
    at eval (webpack-internal:///../../node_modules/@tamagui/web/dist/cjs/createComponent.js:174:70)
    at IndexScreen (webpack-internal:///../../packages/app/features/calendar/index-screen.tsx:31:92)
    at Page
    at div
    at eval (webpack-internal:///../../node_modules/@tamagui/web/dist/cjs/createComponent.js:174:70)
    at div
    at eval (webpack-internal:///../../node_modules/@tamagui/web/dist/cjs/createComponent.js:174:70)
    at HomeLayout (webpack-internal:///../../packages/app/features/home/layout.web.tsx:32:23)
    at QueryClientProvider (file:///Users/rdewolff/Projects/meetme/unistack/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.mjs:40:3)
    at QueryClientProvider (webpack-internal:///../../packages/app/provider/react-query/QueryProvider.tsx:16:32)
    at ToastImperativeProvider (webpack-internal:///../../node_modules/@tamagui/toast/dist/esm/ToastImperative.js:36:3)
    at Provider (webpack-internal:///../../node_modules/@tamagui/create-context/dist/esm/create-context.js:37:15)
    at Provider (webpack-internal:///../../node_modules/@tamagui/create-context/dist/esm/create-context.js:37:15)
    at CollectionProvider (webpack-internal:///../../node_modules/@tamagui/collection/dist/esm/Collection.js:26:13)
    at ToastProvider (webpack-internal:///../../node_modules/@tamagui/toast/dist/esm/ToastProvider.js:30:5)
    at ToastProvider (webpack-internal:///../../packages/app/provider/toast/ToastProvider.tsx:15:26)
    at PortalProviderComponent (webpack-internal:///../../node_modules/@tamagui/portal/dist/esm/GorhomPortal.js:142:3)
    at Theme2 (webpack-internal:///../../node_modules/@tamagui/web/dist/cjs/views/Theme.js:44:13)
```
and
```
client.js:1 Warning: propTypes was defined as an instance property on ProxyWorm - Check excludeReactNativeWebExports. Use a static property to define propTypes instead.
    at ProxyWorm - Check excludeReactNativeWebExports
    at div
    at eval (webpack-internal:///../../node_modules/react-native-web/dist/exports/View/index.js:66:27)
    at _CalendarHeader (webpack-internal:///../../node_modules/react-native-big-calendar/build/index.es.js:1038:24)
    at _CalendarContainer (webpack-internal:///../../node_modules/react-native-big-calendar/build/index.es.js:1145:21)
    at _Calendar (webpack-internal:///../../node_modules/react-native-big-calendar/build/index.es.js:1225:17)
    at div
    at eval (webpack-internal:///../../node_modules/@tamagui/web/dist/esm/createComponent.js:171:100)
    at IndexScreen (webpack-internal:///../../packages/app/features/calendar/index-screen.tsx:30:92)
```

Any idea what's causing this and how to fix it?

Do you have a link to a repo where it works with Next.js I could check?

**Comment by rdewolff** [comment]
This issue was due to `tamagui`. For the record, it can be fixed by commenting the following line in `next.config.js`:

```
    // excludeReactNativeWebExports: ['Switch', 'ProgressBar', 'Picker', 'CheckBox', 'Touchable', 'Animated', 'FlatList', 'Modal'],
```

In the section for tamagui:

```

const plugins = [
  withTamagui({
    themeBuilder: {
      input: "../../packages/ui/src/themes/theme.ts",
      output: "../../packages/ui/src/themes/theme-generated.ts",
    },
    config: './tamagui.config.ts',
    components: ['tamagui', '@my/ui'],
    importsWhitelist: ['constants.js', 'colors.js'],
    outputCSS: process.env.NODE_ENV === 'production' ? './public/tamagui.css' : null,
    logTimings: true,
    disableExtraction,
    // experiment - reduced bundle size react-native-web
    useReactNativeWebLite: false,
    shouldExtract: (path) => {
      if (path.includes(join('packages', 'app'))) {
        return true
      }
    },
    // excludeReactNativeWebExports: ['Switch', 'ProgressBar', 'Picker', 'CheckBox', 'Touchable', 'Animated', 'FlatList', 'Modal'],
  }),
]
```

**Comment by acro5piano** [comment]
@rdewolff Thank you for sharing the solution!
